sonar.organization=celerik
sonar.projectKey=celerik_android-kotlin-boilerplate

sonar.projectName=Android-Kotlin-Boilerplate

sonar.language=kotlin
sonar.sourceEncoding=UTF-8

sonar.sources=app/src/main,core/common/src/main,core/network/src/main,core/data/src/main,core/domain/src/main,core/ui/src/main,feature/home/src/main
sonar.exclusions=**/build/**,**/*.xml,**/test/**
sonar.coverage.exclusions=**/test/**,**/androidTest/**,**/testing/**
