fastlane_version "2.220.0"

default_platform(:android)

platform :android do

  desc "Run all checks: lint + tests"
  lane :run_checks do
    gradle(task: "ktlintCheck")
    gradle(task: "detekt")
    gradle(task: "test")
  end

  desc "Build staging APK"
  lane :build_staging do |options|
    gradle(
      task: "assemble",
      flavor: "staging",
      build_type: "release",
      flags: "-Pversion_code=#{options[:build_number]} -Pversion_name='#{options[:version_name]}'"
    )
  end

  desc "Build production APK"
  lane :build_production do |options|
    gradle(
      task: "assemble",
      flavor: "production",
      build_type: "release",
      flags: "-Pversion_code=#{options[:build_number]} -Pversion_name='#{options[:version_name]}'"
    )
  end

end
